import type { Template } from "./types";

export const WANI_READY: Template[] = [
    // ── Store Templates (Utility & Marketing) ──
    {
        id: "wani_order_confirm_ar", name: "wani_order_confirm",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "store",
        headerType: "none",
        body: "مرحباً {{1}} 👋\n\nاستلمنا طلبك رقم #{{2}} بإجمالي {{3}} جنيه.\n\nتأكيد إنك عايز الأوردر ده يتنفذ فعلاً؟",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "أيوه، أكّد الأوردر", value: "CONFIRM_ORDER" },
            { type: "quick_reply", text: "لأ، إلغاء", value: "CANCEL_ORDER" },
        ],
        exampleVars: ["أحمد", "ORD-12345", "١٢٥ ج.م"],
    },
    {
        id: "wani_order_confirm_en", name: "wani_order_confirm",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "store",
        headerType: "none",
        body: "Hello {{1}} 👋\n\nWe received your order #{{2}} for {{3}}.\n\nPlease confirm you want to proceed.",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "Yes, Confirm", value: "CONFIRM_ORDER" },
            { type: "quick_reply", text: "No, Cancel", value: "CANCEL_ORDER" },
        ],
        exampleVars: ["Ahmed", "ORD-12345", "$50"],
    },
    {
        id: "wani_order_shipped_ar", name: "wani_order_shipped",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "store",
        headerType: "none",
        body: "مرحباً {{1}} 📦\n\nطلبك رقم {{2}} في طريقه إليك! 🚚\nرقم التتبع: {{3}}\n\nتوقع وصوله خلال 2-4 أيام.",
        footer: "Wani Store",
        exampleVars: ["مريم", "ORD-12345", "TRK-789"],
    },
    {
        id: "wani_order_shipped_en", name: "wani_order_shipped",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "store",
        headerType: "none",
        body: "Hi {{1}} 📦\n\nYour order {{2}} is on its way! 🚚\nTracking: {{3}}\n\nExpect it in 2-4 days.",
        footer: "Wani Store",
        exampleVars: ["Maryam", "ORD-12345", "TRK-789"],
    },
    {
        id: "wani_cart_abandon_ar", name: "wani_cart_abandon",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "store",
        headerType: "image",
        body: "مرحباً {{1}} 🛒\n\nنسيت {{2}} في سلتك!\nالإجمالي: {{3}}\n\nأكمل طلبك الآن قبل نفاد المخزون 👇\n{{4}}\n\nبانتظارك! 📦",
        exampleVars: ["سارة", "قميص قطني أزرق", "٢٤٠ ج.م", "https://store.example.com/cart"],
        footer: "Wani Store",
    },
    {
        id: "wani_cart_abandon_en", name: "wani_cart_abandon",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "store",
        headerType: "image",
        body: "Hello {{1}} 🛒\n\nYou left {{2}} in your cart!\nTotal: {{3}}\n\nComplete your order before stock runs out 👇\n{{4}}\n\nWaiting for you! 📦",
        exampleVars: ["Sarah", "Blue Cotton Shirt", "$24", "https://store.example.com/cart"],
        footer: "Wani Store",
    },

    // ── Follow-up Templates ──
    {
        id: "wani_shipping_followup_ar", name: "wani_shipping_followup",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "مرحبًا {{1}} 👋\n\nنتمنى أن يكون طلبك قد وصل إليك.\n\nهل استلمت طلبك؟",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "استلمته", value: "delivered" },
            { type: "quick_reply", text: "لسه موصلش", value: "not_delivered" },
            { type: "quick_reply", text: "حصلت مشكلة", value: "problem" },
        ],
        exampleVars: ["أحمد"],
    },
    {
        id: "wani_shipping_followup_en", name: "wani_shipping_followup",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "Hello {{1}} 👋\n\nWe hope your order has arrived.\n\nDid you receive it?",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "Received", value: "delivered" },
            { type: "quick_reply", text: "Not yet", value: "not_delivered" },
            { type: "quick_reply", text: "Got a problem", value: "problem" },
        ],
        exampleVars: ["Ahmed"],
    },
    {
        id: "wani_abandoned_cart_followup_ar", name: "wani_abandoned_cart_followup",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "مرحبًا {{1}} 👋\n\nلاحظنا أنك لم تُكمل طلبك حتى الآن.\n\nهل ما زلت ترغب في إتمامه؟",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "أريد إكمال الطلب", value: "continue_order" },
            { type: "quick_reply", text: "لدي استفسار", value: "ask_question" },
            { type: "quick_reply", text: "غير مهتم", value: "not_interested" },
        ],
        exampleVars: ["أحمد"],
    },
    {
        id: "wani_abandoned_cart_followup_en", name: "wani_abandoned_cart_followup",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "Hi {{1}} 👋\n\nWe noticed you haven't completed your order yet.\n\nWould you like to finish it?",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "Continue Order", value: "continue_order" },
            { type: "quick_reply", text: "I have a question", value: "ask_question" },
            { type: "quick_reply", text: "Not interested", value: "not_interested" },
        ],
        exampleVars: ["Ahmed"],
    },
    {
        id: "wani_campaign_followup_generic_ar", name: "wani_campaign_followup_generic",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "مرحبًا {{1}} 👋\n\nهل ما زلت مهتمًا بهذا العرض؟",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "اطلب الآن", value: "want_order" },
            { type: "quick_reply", text: "لدي استفسار", value: "has_question" },
            { type: "quick_reply", text: "ليس الآن", value: "not_interested" },
        ],
        exampleVars: ["أحمد"],
    },
    {
        id: "wani_campaign_followup_generic_en", name: "wani_campaign_followup_generic",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "Hello {{1}} 👋\n\nAre you still interested in this offer?",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "Order Now", value: "want_order" },
            { type: "quick_reply", text: "I have a question", value: "has_question" },
            { type: "quick_reply", text: "Not now", value: "not_interested" },
        ],
        exampleVars: ["Ahmed"],
    },
    {
        id: "wani_campaign_followup_discount_ar", name: "wani_campaign_followup_discount",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "مرحبًا {{1}} 🎯\n\nالخصم اللي بعتناهولك لسه متاح لوقت محدود.\n\nهل جربت العرض؟",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "اطلب الآن", value: "want_order" },
            { type: "quick_reply", text: "لدي استفسار", value: "has_question" },
            { type: "quick_reply", text: "ليس الآن", value: "not_interested" },
        ],
        exampleVars: ["سارة"],
    },
    {
        id: "wani_campaign_followup_discount_en", name: "wani_campaign_followup_discount",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "Hi {{1}} 🎯\n\nThe discount we sent is still available for a limited time.\n\nDid you try the offer?",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "Order Now", value: "want_order" },
            { type: "quick_reply", text: "I have a question", value: "has_question" },
            { type: "quick_reply", text: "Not now", value: "not_interested" },
        ],
        exampleVars: ["Sarah"],
    },
    {
        id: "wani_campaign_followup_launch_ar", name: "wani_campaign_followup_launch",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "مرحبًا {{1}} 🚀\n\nشفت المنتج الجديد اللي بعتناه؟\n\nهل حابب تعرف تفاصيله؟",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "اطلب الآن", value: "want_order" },
            { type: "quick_reply", text: "لدي استفسار", value: "has_question" },
            { type: "quick_reply", text: "ليس الآن", value: "not_interested" },
        ],
        exampleVars: ["مريم"],
    },
    {
        id: "wani_campaign_followup_launch_en", name: "wani_campaign_followup_launch",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "followup",
        headerType: "none",
        body: "Hello {{1}} 🚀\n\nDid you see the new product we sent?\n\nWould you like to know more details?",
        footer: "Wani Store",
        buttons: [
            { type: "quick_reply", text: "Order Now", value: "want_order" },
            { type: "quick_reply", text: "I have a question", value: "has_question" },
            { type: "quick_reply", text: "Not now", value: "not_interested" },
        ],
        exampleVars: ["Maryam"],
    },

    // ── Campaign Templates (12 templates: 6 Marketing, 6 Utility) ──
    // Marketing Campaigns
    {
        id: "wani_campaign_eid_sale_ar", name: "wani_campaign_eid_sale",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا بك يا {{1}} 🎉\n\nبمناسبة العيد السعيد، يسعدنا تقديم خصم خاص بنسبة {{2}} على جميع المنتجات في متجرنا.\n\nاستخدم كود الخصم {{3}} عند إتمام عملية الشراء.\nالعرض ساري ومتاح حتى تاريخ {{4}} فلا تفوت الفرصة!",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "تسوق الآن", value: "https://wani.store/sale" }],
        exampleVars: ["أحمد", "20%", "EID20", "نهاية الأسبوع"],
    },
    {
        id: "wani_campaign_eid_sale_en", name: "wani_campaign_eid_sale",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} 🎉\n\nCelebrate Eid with an exclusive {{2}} discount on all products in our store!\n\nUse your promo code {{3}} during checkout.\nThis special offer is valid until {{4}} so don't miss out!",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Shop Now", value: "https://wani.store/sale" }],
        exampleVars: ["Ahmed", "20%", "EID20", "the weekend"],
    },
    {
        id: "wani_campaign_black_friday_ar", name: "wani_campaign_black_friday",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا بك يا {{1}} 🖤\n\nعروض البلاك فرايداي الكبرى بدأت الآن في متجرنا!\nاستمتع بخصومات حصرية تصل إلى {{2}} على أفضل المنتجات مبيعاً.\n\nتفضل بزيارة متجرنا وتسوق الآن قبل نفاد الكمية المتاحة.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "تسوق الآن", value: "https://wani.store/black-friday" }],
        exampleVars: ["سارة", "50%"],
    },
    {
        id: "wani_campaign_black_friday_en", name: "wani_campaign_black_friday",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} 🖤\n\nBlack Friday deals have officially started in our store!\nEnjoy exclusive discounts up to {{2}} on our best-selling items.\n\nVisit our store and shop now before stocks run out.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Shop Now", value: "https://wani.store/black-friday" }],
        exampleVars: ["Sarah", "50%"],
    },
    {
        id: "wani_campaign_new_collection_ar", name: "wani_campaign_new_collection",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا بك يا {{1}} ✨\n\nتشكيلتنا الجديدة والحصرية وصلت الآن إلى متجرنا!\nاكتشف أحدث التصميمات والمنتجات المميزة التي أضفناها اليوم.\n\nيمكنك تصفح التشكيلة الكاملة والطلب مباشرة عبر الرابط أدناه.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "تصفح التشكيلة", value: "https://wani.store/new-collection" }],
        exampleVars: ["مريم"],
    },
    {
        id: "wani_campaign_new_collection_en", name: "wani_campaign_new_collection",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} ✨\n\nOur brand new collection has just arrived in our store!\nDiscover the latest designs and featured items added today.\n\nBrowse the complete collection and place your order directly below.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Browse Collection", value: "https://wani.store/new-collection" }],
        exampleVars: ["Maryam"],
    },
    {
        id: "wani_campaign_flash_sale_ar", name: "wani_campaign_flash_sale",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا بك يا {{1}} ⚡\n\nعرض خاطف وحصري لمدة 24 ساعة فقط في متجرنا!\nاحصل على عرض {{2}} عند تسوقك اليوم.\n\nسارع بالطلب الآن فالكميات محدودة جداً.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "اغتنم العرض", value: "https://wani.store/flash-sale" }],
        exampleVars: ["أحمد", "شحن مجاني"],
    },
    {
        id: "wani_campaign_flash_sale_en", name: "wani_campaign_flash_sale",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} ⚡\n\nExclusive 24-hour flash sale available now in our store!\nGet a special offer of {{2}} when shopping today.\n\nOrder now while quantities last.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Shop Flash Sale", value: "https://wani.store/flash-sale" }],
        exampleVars: ["Ahmed", "free shipping"],
    },
    {
        id: "wani_campaign_loyalty_reward_ar", name: "wani_campaign_loyalty_reward",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا بك يا {{1}} 🎁\n\nتقديراً لولائك وثقتك بنا، تمت إضافة رصيد مكافآت بقيمة {{2}} نقطة إلى حسابك!\nيمكنك استخدامه وتطبيقه في طلبك القادم من المتجر.\n\nشكراً لاختيارك الدائم لنا.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "استخدم المكافأة", value: "https://wani.store/rewards" }],
        exampleVars: ["أحمد", "500"],
    },
    {
        id: "wani_campaign_loyalty_reward_en", name: "wani_campaign_loyalty_reward",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} 🎁\n\nAs a valued customer, we have added {{2}} reward points to your account!\nYou can apply them towards your next order in our store.\n\nThank you for shopping with us.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Use Points", value: "https://wani.store/rewards" }],
        exampleVars: ["Ahmed", "500"],
    },
    {
        id: "wani_campaign_win_back_ar", name: "wani_campaign_win_back",
        category: "MARKETING", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا بك يا {{1}} 👋\n\nلقد اشتقنا لتواجدك معنا في المتجر!\n\nيسعدنا أن نقدم لك خصماً خاصاً بنسبة {{2}} على طلبك القادم.\nاستخدم كود الخصم {{3}} عند الدفع واستمتع بتجربة تسوق مميزة.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "تسوق الآن", value: "https://wani.store/offers" }],
        exampleVars: ["محمد", "15%", "MISSYOU15"],
    },
    {
        id: "wani_campaign_win_back_en", name: "wani_campaign_win_back",
        category: "MARKETING", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} 👋\n\nWe missed having you in our store!\n\nWe would love to offer you an exclusive {{2}} discount on your next order.\nUse promo code {{3}} during checkout and enjoy shopping with us.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Shop Now", value: "https://wani.store/offers" }],
        exampleVars: ["Mohammed", "15%", "MISSYOU15"],
    },

    // Utility Campaigns
    {
        id: "wani_campaign_store_maintenance_ar", name: "wani_campaign_store_maintenance",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا {{1}} 🛠️\n\nنود إعلامك بوجود صيانة مجدولة للمتجر يوم {{2}} من الساعة {{3}}.\nقد تتأثر بعض الخدمات مؤقتًا.\n\nشكراً لتفهمك.",
        footer: "Wani Store",
        exampleVars: ["أحمد", "الأحد القادم", "10 صباحاً"],
    },
    {
        id: "wani_campaign_store_maintenance_en", name: "wani_campaign_store_maintenance",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} 🛠️\n\nWe want to inform you of scheduled maintenance on {{2}} starting at {{3}}.\nSome services may be temporarily affected.\n\nThank you for understanding.",
        footer: "Wani Store",
        exampleVars: ["Ahmed", "Next Sunday", "10 AM"],
    },
    {
        id: "wani_campaign_policy_update_ar", name: "wani_campaign_policy_update",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا {{1}} 📢\n\nقمنا بتحديث سياسة الاسترجاع الخاصة بنا.\nيرجى مراجعة السياسة الجديدة من خلال الرابط أدناه لمعرفة المزيد من التفاصيل.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "قراءة السياسة", value: "https://store.com/policy" }],
        exampleVars: ["أحمد"],
    },
    {
        id: "wani_campaign_policy_update_en", name: "wani_campaign_policy_update",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hi {{1}} 📢\n\nWe have updated our return policy.\nPlease review the new policy via the link below for more details.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Read Policy", value: "https://store.com/policy" }],
        exampleVars: ["Ahmed"],
    },
    {
        id: "wani_campaign_shipping_delay_ar", name: "wani_campaign_shipping_delay",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا {{1}} ⚠️\n\nنعتذر لإبلاغك بوجود تأخير عام في الشحن بسبب {{2}}.\nنعمل جاهدين لتوصيل طلباتكم في أقرب وقت.\n\nشكراً لصبركم.",
        footer: "Wani Store",
        exampleVars: ["مريم", "سوء الأحوال الجوية"],
    },
    {
        id: "wani_campaign_shipping_delay_en", name: "wani_campaign_shipping_delay",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} ⚠️\n\nWe apologize for a general shipping delay due to {{2}}.\nWe are working hard to deliver your orders as soon as possible.\n\nThank you for your patience.",
        footer: "Wani Store",
        exampleVars: ["Maryam", "bad weather conditions"],
    },
    {
        id: "wani_campaign_address_update_ar", name: "wani_campaign_address_update",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا {{1}} 📍\n\nلاحظنا عدم اكتمال عنوان الشحن في حسابك.\nلضمان وصول طلباتك المستقبلية بسلاسة، يرجى تحديث بيانات العنوان.\n\nشكراً لتعاونك.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "تحديث العنوان", value: "https://store.com/profile" }],
        exampleVars: ["أحمد"],
    },
    {
        id: "wani_campaign_address_update_en", name: "wani_campaign_address_update",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hi {{1}} 📍\n\nWe noticed your shipping address is incomplete.\nTo ensure smooth delivery of future orders, please update your address details.\n\nThank you.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Update Address", value: "https://store.com/profile" }],
        exampleVars: ["Ahmed"],
    },
    {
        id: "wani_campaign_stock_replenished_ar", name: "wani_campaign_stock_replenished",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا {{1}} 📦\n\nالمنتج الذي كنت تنتظره \"{{2}}\" متوفر الآن في المخزون!\n\nيمكنك طلبه الآن قبل نفاذ الكمية مجدداً.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "اطلب الآن", value: "https://store.com/product" }],
        exampleVars: ["سارة", "ساعة ذكية الإصدار الأخير"],
    },
    {
        id: "wani_campaign_stock_replenished_en", name: "wani_campaign_stock_replenished",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hello {{1}} 📦\n\nThe item you've been waiting for \"{{2}}\" is back in stock!\n\nYou can order it now before it sells out again.",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Order Now", value: "https://store.com/product" }],
        exampleVars: ["Sarah", "Latest Smart Watch"],
    },
    {
        id: "wani_campaign_event_reminder_ar", name: "wani_campaign_event_reminder",
        category: "UTILITY", language: "ar", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "مرحبًا {{1}} 📅\n\nنذكرك بالحدث الخاص بنا \"{{2}}\" الذي سيبدأ غداً الساعة {{3}}.\n\nنتطلع لرؤيتك!",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "تفاصيل الحدث", value: "https://store.com/event" }],
        exampleVars: ["أحمد", "إطلاق المنتج الجديد", "8 مساءً"],
    },
    {
        id: "wani_campaign_event_reminder_en", name: "wani_campaign_event_reminder",
        category: "UTILITY", language: "en", status: "PENDING", isWaniReady: true, group: "campaign",
        headerType: "none",
        body: "Hi {{1}} 📅\n\nThis is a reminder for our event \"{{2}}\" starting tomorrow at {{3}}.\n\nWe look forward to seeing you!",
        footer: "Wani Store",
        buttons: [{ type: "url", text: "Event Details", value: "https://store.com/event" }],
        exampleVars: ["Ahmed", "New Product Launch", "8 PM"],
    },
];
