-- EasyOrders integration rebuild: webhookSecret is no longer forced to equal
-- the Public API Key. It is now the real secret generated by EasyOrders when
-- the webhook is created, and is optional until the user configures it.
-- This is a data-safe, additive change: it only relaxes the NOT NULL
-- constraint. No existing rows are modified or deleted.

ALTER TABLE "EasyOrdersStore" ALTER COLUMN "webhookSecret" DROP NOT NULL;
